from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass(frozen=True)
class WaterChemistry:
    """Current water chemistry state from the latest pool test."""
    test_date: datetime
    fc: Optional[float]
    tc: Optional[float]
    cc: Optional[float]
    ph: Optional[float]
    ta: Optional[float]
    ch: Optional[float]
    cya: Optional[float]
    temp_f: Optional[float]
    csi: Optional[float]
    fc_cya_ratio: Optional[float]


@dataclass(frozen=True)
class ChlorineTargets:
    """FC target range derived from CYA."""
    minimum_fc: Optional[float]
    target_fc_low: Optional[float]
    target_fc_high: Optional[float]


@dataclass(frozen=True)
class RecommendationState:
    """Latest action recommendation generated by the chemistry engine."""
    overall_status: str
    action_reason: str
    liquid_chlorine_needed_gal: Optional[float]
    liquid_chlorine_strength_percent: Optional[float]
    acid_recommendation: str
    chlorine_targets: ChlorineTargets


@dataclass(frozen=True)
class WeatherState:
    """Latest daily weather summary used for pool decision support."""
    date: Optional[datetime]
    high_temp_f: Optional[float]
    uv_index_max: Optional[float]
    rainfall_in: Optional[float]
    solar_radiation_peak: Optional[float]
    avg_temp_f: Optional[float]
    avg_humidity: Optional[float]
    max_wind_gust_mph: Optional[float]


@dataclass(frozen=True)
class PoolState:
    """Canonical current state of the pool for dashboards, reports, and future interfaces."""
    chemistry: WaterChemistry
    recommendation: RecommendationState
    weather: WeatherState
